### ISSUE TITLE
need a temporary version of "above"

### ISSUE THREAD

**Issue by cedardocster** [skx/kpie#12]
I'm using ubuntu 14.04 Mate edition, and when I'm setting windows above() with kpie it seems to mess with other window behaviour that isn't specified in my kpie lua file, i.e. some new windows don't appear above existing windows that don't have "keep on top" set.

Is there an existing way to bring a new window up above other normal windows, but not have the "always on top" set permanently for it?  If not, could you put that in?

**Comment by skx** [comment]
I think what you want is clear:

* The (new) window to be on top of other windows.

But I'm surprised that doesnt' already happen by default.  I thought all window-managers would give new windows the focus and the foreground.  I think I'm a little confused by your comment about above() not working - but have you tried the obvious:

     above()
     focus()
     below()

And does that not work?

**Comment by cedardocster** [comment]
I figured it out (I think): I had to change focus settings using dconf-editor: 

org / mate / marco / general 
and 
org / gnome / desktop / wm / preferences 

to focus-new-windows = smart and focus-mode=click
thanks for your patience
