### ISSUE TITLE
focus() doesn't seem to work

### ISSUE THREAD

**Issue by cedardocster** [skx/kpie#13]
if ( string.find( window_title(), "web search", 1, true ) ) then
	center() above() focus()
end

this centers and brings above, but I can't type in the window until I click the window

(using Ubuntu 14.04 Mate edition)

**Comment by skx** [comment]
We use the `wnck_window_activate()` function for which the documantion says:

> Asks the window manager to make window the active window. The window manager may choose to raise window along with focusing it, and may decide to refuse the request (to not steal the focus if there is a more recent user activity, for example).

I suspect this means that there is little I can do about the problem.

**Comment by skx** [comment]
I guess this is the same as #12.

**Comment by cedardocster** [comment]
Yup, thanks :)
