### ISSUE TITLE
doesn't compile on openSUSE (or other Linux distros)

### ISSUE THREAD

**Issue by aspiers** [skx/kpie#14]
The Makefile makes various unreliable assumptions distro packaging.  For example:
- On openSUSE 13.2, the `lua51-devel` package provides `lua.pc` in `/usr/lib64/pkgconfig`, not `lua5.1.pc`.
- `libwnck-1.0` is older and may not be available on all distros; at least on openSUSE, `zypper install libwnck2-devel` is required
- It assumes the presence of `dpkg-buildflags`, but only exists on `dpkg`-based distros. 

It's also missing calls to `pkg-config` for `gdk`.  This is a quick hack to make it compile on openSUSE (albeit with warnings):

https://github.com/skx/kpie/compare/master...aspiers:opensuse-compile?expand=1

but a better solution would probably be to use autoconf.

**Comment by skx** [comment]
As you say your pull request isn't quite right - it works for you, and breaks it for me.  Still for your personal use I guess that's the way you'd prefer it to be!

I'll dedicate some time over the weekend to convert to using autoconf - It has been many years since I touched it, but it shouldn't be so hard I hope.

Thanks for your interest, and reports.

**Comment by aspiers** [comment]
Thanks, look forward to seeing the results :)

**Comment by skx** [comment]
With the following two files I can run:

     autoreconf --install
     ./configure
     make

I suspect I'm cheating by using `pkg_config`, but if this works for you then I'm happy to commit it, as it is no worse than it used to be.

(`make dist` does build a tarball I can extract and run "./configure && make && make install` with successfully.)

[configure.ac](https://github.com/skx/kpie/files/32231/configure.ac.txt)
[Makefile.am](https://github.com/skx/kpie/files/32232/Makefile.am.txt)

**Comment by aspiers** [comment]
I get

```
configure: error: Need a Lua toolchain with matching versions ('lua' library and 'lua' and 'luac' programs)
```

even though I have lua 5.1 and corresponding development files installed:

```
$ rpm -qil lua51      
Name        : lua51
Version     : 5.1.5
Release     : 10.2.2
Architecture: x86_64
Install Date: Mon 09 Nov 2015 13:52:24 GMT
Group       : System/Libraries
Size        : 323163
License     : MIT
Signature   : RSA/SHA256, Thu 25 Sep 2014 10:07:26 BST, Key ID b88b2fd43dbdc284
Source RPM  : lua51-5.1.5-10.2.2.src.rpm
Build Date  : Thu 25 Sep 2014 10:07:00 BST
Build Host  : cloud101
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://www.lua.org
Summary     : Small Embeddable Language with Simple Procedural Syntax
Description :
Lua is a programming language originally designed for extending
applications, but also frequently used as a general-purpose,
stand-alone language.

Lua combines simple procedural syntax (similar to Pascal) with powerful
data description constructs based on associative arrays and extensible
semantics. Lua is dynamically typed, interpreted from byte codes, and
has automatic memory management, making it ideal for configuration,
scripting, and rapid prototyping. Lua is implemented as a small library
of C functions, written in ANSI C, and the implementation goals are
simplicity, efficiency, portability, and low embedding cost.
Distribution: openSUSE 13.2
/etc/alternatives/lua
/etc/alternatives/lua.1.gz
/etc/alternatives/luac
/etc/alternatives/luac.1.gz
/etc/rpm/macros.lua51
/usr/bin/lua
/usr/bin/lua5.1
/usr/bin/luac
/usr/bin/luac5.1
/usr/lib64/lua
/usr/lib64/lua/5.1
/usr/share/doc/packages/lua51
/usr/share/doc/packages/lua51/COPYRIGHT
/usr/share/doc/packages/lua51/HISTORY
/usr/share/doc/packages/lua51/README
/usr/share/lua
/usr/share/lua/5.1
/usr/share/man/man1/lua.1.gz
/usr/share/man/man1/lua5.1.1.gz
/usr/share/man/man1/luac.1.gz
/usr/share/man/man1/luac5.1.1.gz

$ rpm -qil lua51-devel
Name        : lua51-devel
Version     : 5.1.5
Release     : 10.2.2
Architecture: x86_64
Install Date: Mon 09 Nov 2015 13:52:26 GMT
Group       : Development/Libraries/C and C++
Size        : 1419278
License     : MIT
Signature   : RSA/SHA256, Thu 25 Sep 2014 10:07:26 BST, Key ID b88b2fd43dbdc284
Source RPM  : lua51-5.1.5-10.2.2.src.rpm
Build Date  : Thu 25 Sep 2014 10:07:00 BST
Build Host  : cloud101
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://www.lua.org
Summary     : Development files for lua
Description :
Lua is a programming language originally designed for extending
applications, but also frequently used as a general-purpose,
stand-alone language.

This package contains files needed for embedding lua into your
application.
Distribution: openSUSE 13.2
/usr/include/lauxlib.h
/usr/include/lua.h
/usr/include/lua.hpp
/usr/include/luaconf.h
/usr/include/lualib.h
/usr/lib64/liblua.a
/usr/lib64/liblua.so
/usr/lib64/liblua5.1.so
/usr/lib64/pkgconfig/lua.pc
```

**Comment by aspiers** [comment]
BTW it would be easier for both our testing if you could develop this in a feature branch ;-)  Thanks a lot for working on it!

**Comment by skx** [comment]
Some projects i used branches for, others like this one are mostly "complete" so work goes on the master branch.

I've got a working CentOS7 virtual machine setup now, so I'll work on this further over the weekend. Sorry for the delay!

**Comment by skx** [comment]
Hope this works :)

**Comment by skx** [comment]
I didn't receive any update, but it works on Centos 6/7 so I'm going to regard this as closed at the end of the week :)
