### ISSUE TITLE
not clear what kpie.lua is for

### ISSUE THREAD

**Issue by aspiers** [skx/kpie#16]
What is kpie.lua for?  It looks like an example config file, but in that case it should in the `samples/` directory along with the others.

**Comment by skx** [comment]
The samples were mostly developed to be somewhat interesting self-contained snippets than a full configuration file.  For users who wanted a full configuration file the top-level `kpie.lua` is what I point them at.

**Comment by aspiers** [comment]
Makes sense - in that case the README.md should also explain this.  Thanks for the reply!
