### ISSUE TITLE
how to raise every new window?

### ISSUE THREAD

**Issue by cedardocster** [skx/kpie#21]
How would I use kpie to raise every new window (but not set as "always on top" as with "above()")?

**Comment by skx** [comment]
That's an interesting question; `kpie` operates as windows are first created, and in all (?) window-managers I've ever used that results in the window being at the front.

I guess now you've said this you've made me realize we need a `raise()` (+ matching `lower()`) function.

For the moment I suspect you could run:

        above()
        below()

The first would set the always-on-top-flag, and ensure the window was raised to the top, then the second would remove the flag.  I _suspect_ that would leave it on top ..

**Comment by skx** [comment]
* New release pushed with this change.
* [Binary packages](https://packages.steve.org.uk/kpie/) uploaded for Debian GNU/Linux:
  * stretch, jessie & wheezy.
