### ISSUE TITLE
Availability on Fedora

### ISSUE THREAD

**Issue by orschiro** [skx/kpie#22]
Dear @skx great idea and currently looking for a substitute for devilspie.

Couldn't make the latter work with GNOME Shell to put a zenity window always on top.

Are you aware of a binary package for kpie that I can directly use on Fedora without having to build it from source?

Thank you!

**Comment by skx** [comment]
I am afraid I am not, sorry to be so unhelpful.

**Comment by orschiro** [comment]
No problem Steve! Let me see if I can build it myself. Thank you. Can we
keep this open? Maybe someone jumps in later and can offer an rpm package
or copr. :-)

**Comment by skx** [comment]
Since nothing happened for a year I will close.  I'm open to including a spec-file if one were to be submitted though :)
